// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSDStatus() {
  return window['go']['main']['App']['CheckSDStatus']();
}

export function ConnectToMUD(arg1, arg2) {
  return window['go']['main']['App']['ConnectToMUD'](arg1, arg2);
}

export function DisconnectFromMUD() {
  return window['go']['main']['App']['DisconnectFromMUD']();
}

export function GenerateRoomImage() {
  return window['go']['main']['App']['GenerateRoomImage']();
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetCurrentEntities() {
  return window['go']['main']['App']['GetCurrentEntities']();
}

export function GetCurrentRoom() {
  return window['go']['main']['App']['GetCurrentRoom']();
}

export function GetMapData() {
  return window['go']['main']['App']['GetMapData']();
}

export function GetMapStats() {
  return window['go']['main']['App']['GetMapStats']();
}

export function GetOutput() {
  return window['go']['main']['App']['GetOutput']();
}

export function GetRoomImage() {
  return window['go']['main']['App']['GetRoomImage']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RegenerateRoomImage() {
  return window['go']['main']['App']['RegenerateRoomImage']();
}

export function RegenerateRoomImageWithPrompt(arg1) {
  return window['go']['main']['App']['RegenerateRoomImageWithPrompt'](arg1);
}

export function SaveMapNow() {
  return window['go']['main']['App']['SaveMapNow']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}
