// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToMUD(arg1:string,arg2:string):Promise<void>;

export function DisconnectFromMUD():Promise<void>;

export function GetConnectionStatus():Promise<boolean>;

export function GetOutput():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function SendCommand(arg1:string):Promise<void>;
