// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSDStatus():Promise<boolean>;

export function ConnectToMUD(arg1:string,arg2:string):Promise<void>;

export function DisconnectFromMUD():Promise<void>;

export function GenerateRoomImage():Promise<string>;

export function GetConnectionStatus():Promise<boolean>;

export function GetCurrentRoom():Promise<Record<string, string>>;

export function GetOutput():Promise<Array<string>>;

export function GetRoomImage():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RegenerateRoomImage():Promise<string>;

export function RegenerateRoomImageWithPrompt(arg1:string):Promise<string>;

export function SendCommand(arg1:string):Promise<void>;
